name: efd-ia # Nome do ambiente conda
channels:
  - pytorch
  - nvidia # Necessário para pytorch com GPU
  - conda-forge
  - defaults
dependencies:
  - python=3.10 # Ou a versão que você prefere/precisa
  - pip
  # Dependências Conda principais
  - pdfplumber
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 # Especifique a versão CUDA compatível com seu hardware/drivers
  - faiss-cpu # Ou faiss-gpu se tiver GPU compatível e quiser usar
  - nltk
  - python-dotenv
  # Dependências Pip (LangChain e Transformers são frequentemente atualizados, Pip pode ser mais fácil)
  - pip:
    - langchain>=0.2.0,<0.3.0
    - langchain-community
    - langchain-core
    - langchain-experimental
    - langchain-huggingface
    - transformers[sentencepiece]>=4.0.0,<5.0.0 # Inclui sentencepiece
    - ipykernel # Para usar o ambiente em notebooks Jupyter
    # Adicione quaisquer outras dependências pip aqui 